import type { ClientSource, EventRecord, Session } from "./types"

export const fixtureClientSource: ClientSource = {
  source_key: "claude-desktop-18244",
  client_name: "Claude Desktop",
  pid: 18244,
  protocol_version: "2024-11-05",
  executable: "C:/Program Files/Claude/Claude.exe",
  cwd: "C:/Users/demo",
  first_seen: "2026-04-12T12:00:00Z",
  last_seen: "2026-04-12T12:05:00Z",
  session_count: 1,
}

export const fixtureSession: Session = {
  thread_id: "thread-abc123",
  source_key: fixtureClientSource.source_key,
  model: "gpt-5.4",
  cwd: "C:/Users/demo/project",
  approval_policy: "on-request",
  sandbox: "workspace-write",
  first_seen: "2026-04-12T12:00:05Z",
  last_seen: "2026-04-12T12:04:59Z",
  status: "active",
}

export const fixtureEvents: EventRecord[] = [
  {
    event_id: "evt-1",
    timestamp: "2026-04-12T12:00:05Z",
    proxy_instance_id: "proxy-1",
    source_key: fixtureClientSource.source_key,
    thread_id: fixtureSession.thread_id,
    request_id: "req-1",
    turn_id: "turn-1",
    direction: "codex_to_upstream",
    category: "notification",
    event_type: "session_configured",
    payload: { model: "gpt-5.4" },
  },
  {
    event_id: "evt-2",
    timestamp: "2026-04-12T12:00:10Z",
    proxy_instance_id: "proxy-1",
    source_key: fixtureClientSource.source_key,
    thread_id: fixtureSession.thread_id,
    request_id: "req-1",
    turn_id: "turn-1",
    direction: "codex_to_upstream",
    category: "notification",
    event_type: "session_configured",
    payload: { model: "gpt-5.4" },
  },
  {
    event_id: "evt-3",
    timestamp: "2026-04-12T12:01:00Z",
    proxy_instance_id: "proxy-1",
    source_key: fixtureClientSource.source_key,
    thread_id: fixtureSession.thread_id,
    request_id: "req-2",
    turn_id: "turn-2",
    direction: "codex_to_upstream",
    category: "notification",
    event_type: "exec_command_begin",
    command_call_id: "cmd-1",
    payload: { cmd: ["ls", "-la"] },
  },
  {
    event_id: "evt-4",
    timestamp: "2026-04-12T12:01:02Z",
    proxy_instance_id: "proxy-1",
    source_key: fixtureClientSource.source_key,
    thread_id: fixtureSession.thread_id,
    request_id: "req-2",
    turn_id: "turn-2",
    direction: "codex_to_upstream",
    category: "notification",
    event_type: "exec_command_output_delta",
    command_call_id: "cmd-1",
    payload: { chunk: "file1\nfile2\n" },
  },
  {
    event_id: "evt-5",
    timestamp: "2026-04-12T12:01:03Z",
    proxy_instance_id: "proxy-1",
    source_key: fixtureClientSource.source_key,
    thread_id: fixtureSession.thread_id,
    request_id: "req-2",
    turn_id: "turn-2",
    direction: "codex_to_upstream",
    category: "notification",
    event_type: "exec_command_end",
    command_call_id: "cmd-1",
    payload: { exit_code: 0 },
  },
  {
    event_id: "evt-6",
    timestamp: "2026-04-12T12:04:59Z",
    proxy_instance_id: "proxy-1",
    source_key: fixtureClientSource.source_key,
    thread_id: fixtureSession.thread_id,
    request_id: "req-3",
    turn_id: "turn-3",
    direction: "codex_to_upstream",
    category: "notification",
    event_type: "turn_complete",
    payload: { summary: "done" },
  },
]
