// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_sources.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getClientSource = `-- name: GetClientSource :one
SELECT client_source_key, pid, protocol_version, client_name, client_version,
       capabilities_json, executable_path, command_line, cwd,
       first_seen_at, last_seen_at
FROM client_sources
WHERE client_source_key = ?
`

func (q *Queries) GetClientSource(ctx context.Context, clientSourceKey string) (ClientSource, error) {
	row := q.queryRow(ctx, q.getClientSourceStmt, getClientSource, clientSourceKey)
	var i ClientSource
	err := row.Scan(
		&i.ClientSourceKey,
		&i.Pid,
		&i.ProtocolVersion,
		&i.ClientName,
		&i.ClientVersion,
		&i.CapabilitiesJson,
		&i.ExecutablePath,
		&i.CommandLine,
		&i.Cwd,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listClientSources = `-- name: ListClientSources :many
SELECT client_source_key, pid, protocol_version, client_name, client_version,
       capabilities_json, executable_path, command_line, cwd,
       first_seen_at, last_seen_at
FROM client_sources
ORDER BY last_seen_at DESC
`

func (q *Queries) ListClientSources(ctx context.Context) ([]ClientSource, error) {
	rows, err := q.query(ctx, q.listClientSourcesStmt, listClientSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientSource
	for rows.Next() {
		var i ClientSource
		if err := rows.Scan(
			&i.ClientSourceKey,
			&i.Pid,
			&i.ProtocolVersion,
			&i.ClientName,
			&i.ClientVersion,
			&i.CapabilitiesJson,
			&i.ExecutablePath,
			&i.CommandLine,
			&i.Cwd,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertClientSource = `-- name: UpsertClientSource :exec
INSERT INTO client_sources (
  client_source_key, pid, protocol_version, client_name, client_version,
  capabilities_json, executable_path, command_line, cwd,
  first_seen_at, last_seen_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(client_source_key) DO UPDATE SET
  pid = excluded.pid,
  protocol_version = excluded.protocol_version,
  client_name = excluded.client_name,
  client_version = excluded.client_version,
  capabilities_json = excluded.capabilities_json,
  executable_path = excluded.executable_path,
  command_line = excluded.command_line,
  cwd = excluded.cwd,
  last_seen_at = excluded.last_seen_at
`

type UpsertClientSourceParams struct {
	ClientSourceKey  string
	Pid              int64
	ProtocolVersion  string
	ClientName       string
	ClientVersion    string
	CapabilitiesJson string
	ExecutablePath   sql.NullString
	CommandLine      sql.NullString
	Cwd              sql.NullString
	FirstSeenAt      int64
	LastSeenAt       int64
}

func (q *Queries) UpsertClientSource(ctx context.Context, arg UpsertClientSourceParams) error {
	_, err := q.exec(ctx, q.upsertClientSourceStmt, upsertClientSource,
		arg.ClientSourceKey,
		arg.Pid,
		arg.ProtocolVersion,
		arg.ClientName,
		arg.ClientVersion,
		arg.CapabilitiesJson,
		arg.ExecutablePath,
		arg.CommandLine,
		arg.Cwd,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	return err
}
