// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.appendEventStmt, err = db.PrepareContext(ctx, appendEvent); err != nil {
		return nil, fmt.Errorf("error preparing query AppendEvent: %w", err)
	}
	if q.completeMCPCallStmt, err = db.PrepareContext(ctx, completeMCPCall); err != nil {
		return nil, fmt.Errorf("error preparing query CompleteMCPCall: %w", err)
	}
	if q.getClientSourceStmt, err = db.PrepareContext(ctx, getClientSource); err != nil {
		return nil, fmt.Errorf("error preparing query GetClientSource: %w", err)
	}
	if q.getSessionStmt, err = db.PrepareContext(ctx, getSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetSession: %w", err)
	}
	if q.heartbeatProxyStmt, err = db.PrepareContext(ctx, heartbeatProxy); err != nil {
		return nil, fmt.Errorf("error preparing query HeartbeatProxy: %w", err)
	}
	if q.listActiveProxiesStmt, err = db.PrepareContext(ctx, listActiveProxies); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveProxies: %w", err)
	}
	if q.listAllProxiesStmt, err = db.PrepareContext(ctx, listAllProxies); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllProxies: %w", err)
	}
	if q.listClientSourcesStmt, err = db.PrepareContext(ctx, listClientSources); err != nil {
		return nil, fmt.Errorf("error preparing query ListClientSources: %w", err)
	}
	if q.listMCPCallsBySourceStmt, err = db.PrepareContext(ctx, listMCPCallsBySource); err != nil {
		return nil, fmt.Errorf("error preparing query ListMCPCallsBySource: %w", err)
	}
	if q.listRecentEventsStmt, err = db.PrepareContext(ctx, listRecentEvents); err != nil {
		return nil, fmt.Errorf("error preparing query ListRecentEvents: %w", err)
	}
	if q.listRecentMCPCallsStmt, err = db.PrepareContext(ctx, listRecentMCPCalls); err != nil {
		return nil, fmt.Errorf("error preparing query ListRecentMCPCalls: %w", err)
	}
	if q.listSessionEventsSinceStmt, err = db.PrepareContext(ctx, listSessionEventsSince); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionEventsSince: %w", err)
	}
	if q.listSessionsBySourceStmt, err = db.PrepareContext(ctx, listSessionsBySource); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionsBySource: %w", err)
	}
	if q.markProxyExitedStmt, err = db.PrepareContext(ctx, markProxyExited); err != nil {
		return nil, fmt.Errorf("error preparing query MarkProxyExited: %w", err)
	}
	if q.registerProxyStmt, err = db.PrepareContext(ctx, registerProxy); err != nil {
		return nil, fmt.Errorf("error preparing query RegisterProxy: %w", err)
	}
	if q.upsertClientSourceStmt, err = db.PrepareContext(ctx, upsertClientSource); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertClientSource: %w", err)
	}
	if q.upsertMCPCallStmt, err = db.PrepareContext(ctx, upsertMCPCall); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertMCPCall: %w", err)
	}
	if q.upsertSessionStmt, err = db.PrepareContext(ctx, upsertSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertSession: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.appendEventStmt != nil {
		if cerr := q.appendEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing appendEventStmt: %w", cerr)
		}
	}
	if q.completeMCPCallStmt != nil {
		if cerr := q.completeMCPCallStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing completeMCPCallStmt: %w", cerr)
		}
	}
	if q.getClientSourceStmt != nil {
		if cerr := q.getClientSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getClientSourceStmt: %w", cerr)
		}
	}
	if q.getSessionStmt != nil {
		if cerr := q.getSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionStmt: %w", cerr)
		}
	}
	if q.heartbeatProxyStmt != nil {
		if cerr := q.heartbeatProxyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing heartbeatProxyStmt: %w", cerr)
		}
	}
	if q.listActiveProxiesStmt != nil {
		if cerr := q.listActiveProxiesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveProxiesStmt: %w", cerr)
		}
	}
	if q.listAllProxiesStmt != nil {
		if cerr := q.listAllProxiesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllProxiesStmt: %w", cerr)
		}
	}
	if q.listClientSourcesStmt != nil {
		if cerr := q.listClientSourcesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listClientSourcesStmt: %w", cerr)
		}
	}
	if q.listMCPCallsBySourceStmt != nil {
		if cerr := q.listMCPCallsBySourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMCPCallsBySourceStmt: %w", cerr)
		}
	}
	if q.listRecentEventsStmt != nil {
		if cerr := q.listRecentEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRecentEventsStmt: %w", cerr)
		}
	}
	if q.listRecentMCPCallsStmt != nil {
		if cerr := q.listRecentMCPCallsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRecentMCPCallsStmt: %w", cerr)
		}
	}
	if q.listSessionEventsSinceStmt != nil {
		if cerr := q.listSessionEventsSinceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionEventsSinceStmt: %w", cerr)
		}
	}
	if q.listSessionsBySourceStmt != nil {
		if cerr := q.listSessionsBySourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsBySourceStmt: %w", cerr)
		}
	}
	if q.markProxyExitedStmt != nil {
		if cerr := q.markProxyExitedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markProxyExitedStmt: %w", cerr)
		}
	}
	if q.registerProxyStmt != nil {
		if cerr := q.registerProxyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing registerProxyStmt: %w", cerr)
		}
	}
	if q.upsertClientSourceStmt != nil {
		if cerr := q.upsertClientSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertClientSourceStmt: %w", cerr)
		}
	}
	if q.upsertMCPCallStmt != nil {
		if cerr := q.upsertMCPCallStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertMCPCallStmt: %w", cerr)
		}
	}
	if q.upsertSessionStmt != nil {
		if cerr := q.upsertSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertSessionStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                         DBTX
	tx                         *sql.Tx
	appendEventStmt            *sql.Stmt
	completeMCPCallStmt        *sql.Stmt
	getClientSourceStmt        *sql.Stmt
	getSessionStmt             *sql.Stmt
	heartbeatProxyStmt         *sql.Stmt
	listActiveProxiesStmt      *sql.Stmt
	listAllProxiesStmt         *sql.Stmt
	listClientSourcesStmt      *sql.Stmt
	listMCPCallsBySourceStmt   *sql.Stmt
	listRecentEventsStmt       *sql.Stmt
	listRecentMCPCallsStmt     *sql.Stmt
	listSessionEventsSinceStmt *sql.Stmt
	listSessionsBySourceStmt   *sql.Stmt
	markProxyExitedStmt        *sql.Stmt
	registerProxyStmt          *sql.Stmt
	upsertClientSourceStmt     *sql.Stmt
	upsertMCPCallStmt          *sql.Stmt
	upsertSessionStmt          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                         tx,
		tx:                         tx,
		appendEventStmt:            q.appendEventStmt,
		completeMCPCallStmt:        q.completeMCPCallStmt,
		getClientSourceStmt:        q.getClientSourceStmt,
		getSessionStmt:             q.getSessionStmt,
		heartbeatProxyStmt:         q.heartbeatProxyStmt,
		listActiveProxiesStmt:      q.listActiveProxiesStmt,
		listAllProxiesStmt:         q.listAllProxiesStmt,
		listClientSourcesStmt:      q.listClientSourcesStmt,
		listMCPCallsBySourceStmt:   q.listMCPCallsBySourceStmt,
		listRecentEventsStmt:       q.listRecentEventsStmt,
		listRecentMCPCallsStmt:     q.listRecentMCPCallsStmt,
		listSessionEventsSinceStmt: q.listSessionEventsSinceStmt,
		listSessionsBySourceStmt:   q.listSessionsBySourceStmt,
		markProxyExitedStmt:        q.markProxyExitedStmt,
		registerProxyStmt:          q.registerProxyStmt,
		upsertClientSourceStmt:     q.upsertClientSourceStmt,
		upsertMCPCallStmt:          q.upsertMCPCallStmt,
		upsertSessionStmt:          q.upsertSessionStmt,
	}
}
