// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"context"
	"database/sql"
)

const appendEvent = `-- name: AppendEvent :exec
INSERT INTO events (
  event_id, proxy_instance_id, client_source_key, session_id, turn_id,
  request_id, direction, event_type, occurred_at, raw_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AppendEventParams struct {
	EventID         string
	ProxyInstanceID string
	ClientSourceKey sql.NullString
	SessionID       sql.NullString
	TurnID          sql.NullString
	RequestID       sql.NullString
	Direction       string
	EventType       string
	OccurredAt      int64
	RawJson         []byte
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) error {
	_, err := q.exec(ctx, q.appendEventStmt, appendEvent,
		arg.EventID,
		arg.ProxyInstanceID,
		arg.ClientSourceKey,
		arg.SessionID,
		arg.TurnID,
		arg.RequestID,
		arg.Direction,
		arg.EventType,
		arg.OccurredAt,
		arg.RawJson,
	)
	return err
}

const listRecentEvents = `-- name: ListRecentEvents :many
SELECT event_id, proxy_instance_id, client_source_key, session_id, turn_id,
       request_id, direction, event_type, occurred_at, raw_json
FROM events
ORDER BY occurred_at DESC
LIMIT ?
`

type ListRecentEventsRow struct {
	EventID         string
	ProxyInstanceID string
	ClientSourceKey sql.NullString
	SessionID       sql.NullString
	TurnID          sql.NullString
	RequestID       sql.NullString
	Direction       string
	EventType       string
	OccurredAt      int64
	RawJson         []byte
}

func (q *Queries) ListRecentEvents(ctx context.Context, limit int64) ([]ListRecentEventsRow, error) {
	rows, err := q.query(ctx, q.listRecentEventsStmt, listRecentEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentEventsRow
	for rows.Next() {
		var i ListRecentEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.ProxyInstanceID,
			&i.ClientSourceKey,
			&i.SessionID,
			&i.TurnID,
			&i.RequestID,
			&i.Direction,
			&i.EventType,
			&i.OccurredAt,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionEventsSince = `-- name: ListSessionEventsSince :many
SELECT event_id, proxy_instance_id, client_source_key, session_id, turn_id,
       request_id, direction, event_type, occurred_at, raw_json
FROM events
WHERE session_id = ? AND (? = '' OR event_id > ?)
ORDER BY occurred_at ASC, event_id ASC
LIMIT ?
`

type ListSessionEventsSinceParams struct {
	SessionID sql.NullString
	Column2   interface{}
	EventID   string
	Limit     int64
}

type ListSessionEventsSinceRow struct {
	EventID         string
	ProxyInstanceID string
	ClientSourceKey sql.NullString
	SessionID       sql.NullString
	TurnID          sql.NullString
	RequestID       sql.NullString
	Direction       string
	EventType       string
	OccurredAt      int64
	RawJson         []byte
}

func (q *Queries) ListSessionEventsSince(ctx context.Context, arg ListSessionEventsSinceParams) ([]ListSessionEventsSinceRow, error) {
	rows, err := q.query(ctx, q.listSessionEventsSinceStmt, listSessionEventsSince,
		arg.SessionID,
		arg.Column2,
		arg.EventID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionEventsSinceRow
	for rows.Next() {
		var i ListSessionEventsSinceRow
		if err := rows.Scan(
			&i.EventID,
			&i.ProxyInstanceID,
			&i.ClientSourceKey,
			&i.SessionID,
			&i.TurnID,
			&i.RequestID,
			&i.Direction,
			&i.EventType,
			&i.OccurredAt,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
