// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_calls.sql

package sqlc

import (
	"context"
	"database/sql"
)

const completeMCPCall = `-- name: CompleteMCPCall :exec
UPDATE mcp_calls
SET completed_at = ?, completion_status = ?
WHERE request_id = ?
`

type CompleteMCPCallParams struct {
	CompletedAt      sql.NullInt64
	CompletionStatus sql.NullString
	RequestID        string
}

func (q *Queries) CompleteMCPCall(ctx context.Context, arg CompleteMCPCallParams) error {
	_, err := q.exec(ctx, q.completeMCPCallStmt, completeMCPCall, arg.CompletedAt, arg.CompletionStatus, arg.RequestID)
	return err
}

const listMCPCallsBySource = `-- name: ListMCPCallsBySource :many
SELECT request_id, proxy_instance_id, client_source_key, session_id,
       tool_name, started_at, completed_at, completion_status
FROM mcp_calls
WHERE client_source_key = ?
ORDER BY started_at DESC
`

func (q *Queries) ListMCPCallsBySource(ctx context.Context, clientSourceKey string) ([]McpCall, error) {
	rows, err := q.query(ctx, q.listMCPCallsBySourceStmt, listMCPCallsBySource, clientSourceKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpCall
	for rows.Next() {
		var i McpCall
		if err := rows.Scan(
			&i.RequestID,
			&i.ProxyInstanceID,
			&i.ClientSourceKey,
			&i.SessionID,
			&i.ToolName,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CompletionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMCPCalls = `-- name: ListRecentMCPCalls :many
SELECT request_id, proxy_instance_id, client_source_key, session_id,
       tool_name, started_at, completed_at, completion_status
FROM mcp_calls
ORDER BY started_at DESC
LIMIT ?
`

func (q *Queries) ListRecentMCPCalls(ctx context.Context, limit int64) ([]McpCall, error) {
	rows, err := q.query(ctx, q.listRecentMCPCallsStmt, listRecentMCPCalls, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpCall
	for rows.Next() {
		var i McpCall
		if err := rows.Scan(
			&i.RequestID,
			&i.ProxyInstanceID,
			&i.ClientSourceKey,
			&i.SessionID,
			&i.ToolName,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CompletionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMCPCall = `-- name: UpsertMCPCall :exec
INSERT INTO mcp_calls (
  request_id, proxy_instance_id, client_source_key, session_id,
  tool_name, started_at, completed_at, completion_status
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(request_id) DO UPDATE SET
  session_id = COALESCE(excluded.session_id, mcp_calls.session_id),
  completed_at = COALESCE(excluded.completed_at, mcp_calls.completed_at),
  completion_status = COALESCE(excluded.completion_status, mcp_calls.completion_status)
`

type UpsertMCPCallParams struct {
	RequestID        string
	ProxyInstanceID  string
	ClientSourceKey  string
	SessionID        sql.NullString
	ToolName         string
	StartedAt        int64
	CompletedAt      sql.NullInt64
	CompletionStatus sql.NullString
}

func (q *Queries) UpsertMCPCall(ctx context.Context, arg UpsertMCPCallParams) error {
	_, err := q.exec(ctx, q.upsertMCPCallStmt, upsertMCPCall,
		arg.RequestID,
		arg.ProxyInstanceID,
		arg.ClientSourceKey,
		arg.SessionID,
		arg.ToolName,
		arg.StartedAt,
		arg.CompletedAt,
		arg.CompletionStatus,
	)
	return err
}
