// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type ClientSource struct {
	ClientSourceKey  string
	Pid              int64
	ProtocolVersion  string
	ClientName       string
	ClientVersion    string
	CapabilitiesJson string
	ExecutablePath   sql.NullString
	CommandLine      sql.NullString
	Cwd              sql.NullString
	FirstSeenAt      int64
	LastSeenAt       int64
}

type Event struct {
	EventID         string
	ProxyInstanceID string
	ClientSourceKey sql.NullString
	SessionID       sql.NullString
	TurnID          sql.NullString
	RequestID       sql.NullString
	Direction       string
	EventType       string
	OccurredAt      int64
	RawJson         []byte
	Category        string
	CommandCallID   sql.NullString
	ToolCallID      sql.NullString
}

type McpCall struct {
	RequestID        string
	ProxyInstanceID  string
	ClientSourceKey  string
	SessionID        sql.NullString
	ToolName         string
	StartedAt        int64
	CompletedAt      sql.NullInt64
	CompletionStatus sql.NullString
}

type ProxyInstance struct {
	ProxyInstanceID string
	ClientSourceKey sql.NullString
	Pid             int64
	StartedAt       int64
	LastHeartbeatAt int64
	ExitedAt        sql.NullInt64
}

type Session struct {
	SessionID       string
	ClientSourceKey string
	Model           sql.NullString
	Cwd             sql.NullString
	ApprovalPolicy  sql.NullString
	FirstSeenAt     int64
	LastSeenAt      int64
}
