// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: proxies.sql

package sqlc

import (
	"context"
	"database/sql"
)

const heartbeatProxy = `-- name: HeartbeatProxy :exec
UPDATE proxy_instances
SET last_heartbeat_at = ?
WHERE proxy_instance_id = ?
`

type HeartbeatProxyParams struct {
	LastHeartbeatAt int64
	ProxyInstanceID string
}

func (q *Queries) HeartbeatProxy(ctx context.Context, arg HeartbeatProxyParams) error {
	_, err := q.exec(ctx, q.heartbeatProxyStmt, heartbeatProxy, arg.LastHeartbeatAt, arg.ProxyInstanceID)
	return err
}

const listActiveProxies = `-- name: ListActiveProxies :many
SELECT proxy_instance_id, client_source_key, pid, started_at, last_heartbeat_at, exited_at
FROM proxy_instances
WHERE exited_at IS NULL
ORDER BY started_at DESC
`

func (q *Queries) ListActiveProxies(ctx context.Context) ([]ProxyInstance, error) {
	rows, err := q.query(ctx, q.listActiveProxiesStmt, listActiveProxies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProxyInstance
	for rows.Next() {
		var i ProxyInstance
		if err := rows.Scan(
			&i.ProxyInstanceID,
			&i.ClientSourceKey,
			&i.Pid,
			&i.StartedAt,
			&i.LastHeartbeatAt,
			&i.ExitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllProxies = `-- name: ListAllProxies :many
SELECT proxy_instance_id, client_source_key, pid, started_at, last_heartbeat_at, exited_at
FROM proxy_instances
ORDER BY started_at DESC
`

func (q *Queries) ListAllProxies(ctx context.Context) ([]ProxyInstance, error) {
	rows, err := q.query(ctx, q.listAllProxiesStmt, listAllProxies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProxyInstance
	for rows.Next() {
		var i ProxyInstance
		if err := rows.Scan(
			&i.ProxyInstanceID,
			&i.ClientSourceKey,
			&i.Pid,
			&i.StartedAt,
			&i.LastHeartbeatAt,
			&i.ExitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProxyExited = `-- name: MarkProxyExited :exec
UPDATE proxy_instances
SET exited_at = ?
WHERE proxy_instance_id = ?
`

type MarkProxyExitedParams struct {
	ExitedAt        sql.NullInt64
	ProxyInstanceID string
}

func (q *Queries) MarkProxyExited(ctx context.Context, arg MarkProxyExitedParams) error {
	_, err := q.exec(ctx, q.markProxyExitedStmt, markProxyExited, arg.ExitedAt, arg.ProxyInstanceID)
	return err
}

const registerProxy = `-- name: RegisterProxy :exec
INSERT INTO proxy_instances (
  proxy_instance_id, client_source_key, pid, started_at, last_heartbeat_at
) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(proxy_instance_id) DO UPDATE SET
  client_source_key = excluded.client_source_key,
  pid = excluded.pid,
  last_heartbeat_at = excluded.last_heartbeat_at,
  exited_at = NULL
`

type RegisterProxyParams struct {
	ProxyInstanceID string
	ClientSourceKey sql.NullString
	Pid             int64
	StartedAt       int64
	LastHeartbeatAt int64
}

func (q *Queries) RegisterProxy(ctx context.Context, arg RegisterProxyParams) error {
	_, err := q.exec(ctx, q.registerProxyStmt, registerProxy,
		arg.ProxyInstanceID,
		arg.ClientSourceKey,
		arg.Pid,
		arg.StartedAt,
		arg.LastHeartbeatAt,
	)
	return err
}
