// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getSession = `-- name: GetSession :one
SELECT session_id, client_source_key, model, cwd, approval_policy, title,
       first_seen_at, last_seen_at
FROM sessions
WHERE session_id = ?
`

type GetSessionRow struct {
	SessionID       string
	ClientSourceKey string
	Model           sql.NullString
	Cwd             sql.NullString
	ApprovalPolicy  sql.NullString
	Title           sql.NullString
	FirstSeenAt     int64
	LastSeenAt      int64
}

func (q *Queries) GetSession(ctx context.Context, sessionID string) (GetSessionRow, error) {
	row := q.queryRow(ctx, q.getSessionStmt, getSession, sessionID)
	var i GetSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.ClientSourceKey,
		&i.Model,
		&i.Cwd,
		&i.ApprovalPolicy,
		&i.Title,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listSessionsBySource = `-- name: ListSessionsBySource :many
SELECT session_id, client_source_key, model, cwd, approval_policy, title,
       first_seen_at, last_seen_at
FROM sessions
WHERE client_source_key = ?
ORDER BY last_seen_at DESC
`

type ListSessionsBySourceRow struct {
	SessionID       string
	ClientSourceKey string
	Model           sql.NullString
	Cwd             sql.NullString
	ApprovalPolicy  sql.NullString
	Title           sql.NullString
	FirstSeenAt     int64
	LastSeenAt      int64
}

func (q *Queries) ListSessionsBySource(ctx context.Context, clientSourceKey string) ([]ListSessionsBySourceRow, error) {
	rows, err := q.query(ctx, q.listSessionsBySourceStmt, listSessionsBySource, clientSourceKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsBySourceRow
	for rows.Next() {
		var i ListSessionsBySourceRow
		if err := rows.Scan(
			&i.SessionID,
			&i.ClientSourceKey,
			&i.Model,
			&i.Cwd,
			&i.ApprovalPolicy,
			&i.Title,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (
  session_id, client_source_key, model, cwd, approval_policy,
  first_seen_at, last_seen_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(session_id) DO UPDATE SET
  client_source_key = excluded.client_source_key,
  model = COALESCE(excluded.model, sessions.model),
  cwd = COALESCE(excluded.cwd, sessions.cwd),
  approval_policy = COALESCE(excluded.approval_policy, sessions.approval_policy),
  last_seen_at = excluded.last_seen_at
`

type UpsertSessionParams struct {
	SessionID       string
	ClientSourceKey string
	Model           sql.NullString
	Cwd             sql.NullString
	ApprovalPolicy  sql.NullString
	FirstSeenAt     int64
	LastSeenAt      int64
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.exec(ctx, q.upsertSessionStmt, upsertSession,
		arg.SessionID,
		arg.ClientSourceKey,
		arg.Model,
		arg.Cwd,
		arg.ApprovalPolicy,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	return err
}
